<a href="https://colab.research.google.com/github/dsogden/NLP-Specialization/blob/main/Chap3_W1_Hidden_State.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Weights

In [4]:
w_hh = np.full((3, 2), 1)
w_hx = np.full((3, 3), 9)
print(f'Weights h = {w_hh}')
print(f'Weights h.shape = {w_hh.shape}')
print(f'Weights x = {w_hx}')
print(f'Weights x.shape = {w_hx.shape}')

concat = np.concatenate([w_hh, w_hx], axis=1)
print(f'New matrix: {concat}')

Weights h = [[1 1]
 [1 1]
 [1 1]]
Weights h.shape = (3, 2)
Weights x = [[9 9 9]
 [9 9 9]
 [9 9 9]]
Weights x.shape = (3, 3)
New matrix: [[1 1 9 9 9]
 [1 1 9 9 9]
 [1 1 9 9 9]]


### Hidden state and inputs

In [6]:
h_t_prev = np.full((2, 1), 1)
x_t = np.full((3, 1), 9)

ax_1 = np.concatenate(
    (h_t_prev, x_t), axis=0
)  # note the difference in axis parameter vs earlier
print("option 1 : concatenate\n")
print("ax_1 :")
print(ax_1)
print("ax_1 shape :", ax_1.shape, "\n")

# Option 2: vstack
ax_2 = np.vstack((h_t_prev, x_t))
print("option 2 : vstack\n")
print("ax_2 :")
print(ax_2)
print("ax_2 shape :", ax_2.shape)

option 1 : concatenate

ax_1 :
[[1]
 [1]
 [9]
 [9]
 [9]]
ax_1 shape : (5, 1) 

option 2 : vstack

ax_2 :
[[1]
 [1]
 [9]
 [9]
 [9]]
ax_2 shape : (5, 1)


### Verify formulas

In [8]:
w_hh = np.full((3, 2), 1)
w_hx = np.full((3, 3), 9)
h_t_prev = np.full((2, 1), 1)
x_t = np.full((3, 1), 9)

stack_1 = np.hstack((w_hh, w_hx))
stack_2 = np.vstack((h_t_prev, x_t))

output = np.matmul(stack_1, stack_2)
print(output.shape, output)

(3, 1) [[245]
 [245]
 [245]]


In [10]:
output = np.matmul(w_hh, h_t_prev) + np.matmul(w_hx, x_t)
print(output.shape, output)

(3, 1) [[245]
 [245]
 [245]]
